const cardImageMap: Record<string, ReturnType<typeof require>> = {
  // Aces
  Ac: require('../assets/cards/ace_of_clubs.png'),
  Ad: require('../assets/cards/ace_of_diamonds.png'),
  Ah: require('../assets/cards/ace_of_hearts.png'),
  As: require('../assets/cards/ace_of_spades.png'),
  // Twos
  '2c': require('../assets/cards/2_of_clubs.png'),
  '2d': require('../assets/cards/2_of_diamonds.png'),
  '2h': require('../assets/cards/2_of_hearts.png'),
  '2s': require('../assets/cards/2_of_spades.png'),
  // Wild deuces (Deuces Wild game)
  Wc: require('../assets/cards/2w_of_clubs.png'),
  Wd: require('../assets/cards/2w_of_diamonds.png'),
  Wh: require('../assets/cards/2w_of_hearts.png'),
  Ws: require('../assets/cards/2w_of_spades.png'),
  // Threes
  '3c': require('../assets/cards/3_of_clubs.png'),
  '3d': require('../assets/cards/3_of_diamonds.png'),
  '3h': require('../assets/cards/3_of_hearts.png'),
  '3s': require('../assets/cards/3_of_spades.png'),
  // Fours
  '4c': require('../assets/cards/4_of_clubs.png'),
  '4d': require('../assets/cards/4_of_diamonds.png'),
  '4h': require('../assets/cards/4_of_hearts.png'),
  '4s': require('../assets/cards/4_of_spades.png'),
  // Fives
  '5c': require('../assets/cards/5_of_clubs.png'),
  '5d': require('../assets/cards/5_of_diamonds.png'),
  '5h': require('../assets/cards/5_of_hearts.png'),
  '5s': require('../assets/cards/5_of_spades.png'),
  // Sixes
  '6c': require('../assets/cards/6_of_clubs.png'),
  '6d': require('../assets/cards/6_of_diamonds.png'),
  '6h': require('../assets/cards/6_of_hearts.png'),
  '6s': require('../assets/cards/6_of_spades.png'),
  // Sevens
  '7c': require('../assets/cards/7_of_clubs.png'),
  '7d': require('../assets/cards/7_of_diamonds.png'),
  '7h': require('../assets/cards/7_of_hearts.png'),
  '7s': require('../assets/cards/7_of_spades.png'),
  // Eights
  '8c': require('../assets/cards/8_of_clubs.png'),
  '8d': require('../assets/cards/8_of_diamonds.png'),
  '8h': require('../assets/cards/8_of_hearts.png'),
  '8s': require('../assets/cards/8_of_spades.png'),
  // Nines
  '9c': require('../assets/cards/9_of_clubs.png'),
  '9d': require('../assets/cards/9_of_diamonds.png'),
  '9h': require('../assets/cards/9_of_hearts.png'),
  '9s': require('../assets/cards/9_of_spades.png'),
  // Tens
  Tc: require('../assets/cards/10_of_clubs.png'),
  Td: require('../assets/cards/10_of_diamonds.png'),
  Th: require('../assets/cards/10_of_hearts.png'),
  Ts: require('../assets/cards/10_of_spades.png'),
  // Jacks
  Jc: require('../assets/cards/jack_of_clubs.png'),
  Jd: require('../assets/cards/jack_of_diamonds.png'),
  Jh: require('../assets/cards/jack_of_hearts.png'),
  Js: require('../assets/cards/jack_of_spades.png'),
  // Queens
  Qc: require('../assets/cards/queen_of_clubs.png'),
  Qd: require('../assets/cards/queen_of_diamonds.png'),
  Qh: require('../assets/cards/queen_of_hearts.png'),
  Qs: require('../assets/cards/queen_of_spades.png'),
  // Kings
  Kc: require('../assets/cards/king_of_clubs.png'),
  Kd: require('../assets/cards/king_of_diamonds.png'),
  Kh: require('../assets/cards/king_of_hearts.png'),
  Ks: require('../assets/cards/king_of_spades.png'),
  // Card back (face-down / empty slot)
  cardback: require('../assets/cards/blank.png'),
}

export default cardImageMap
